#+TITLE: modeline-major-mode.el
#+OPTIONS: toc:nil
#+OPTIONS: html-postamble:nil
#+HTML_HEAD: <style>code { font-size: 1.5em; }</style>

A small library for ~doom-modeline~ to display the major-mode icon instead of the text name.

* Features

This package provides a ~doom-modeline~ segment:

- ~modeline-major-mode-icon~: Displays *only* the major-mode icon.

* Installation & Usage

1. Place ~modeline-major-mode.el~ in your Emacs ~load-path~.
2. Add ~(require 'modeline-major-mode)~ to your Emacs configuration.
3. Define a custom ~doom-modeline~ layout using one of the new segments.

Using Doom Emacs.

#+begin_src emacs-lisp
(package! modeline-major-mode
  :recipe (:host github
           :repo "rgkirch/modeline-major-mode"))
#+end_src

The default (as of time of writing) doom modeline with the icon added as the last item.

[[file:~/.config/emacs/.local/straight/repos/doom-modeline/doom-modeline.el::(doom-modeline-def-modeline 'main]]

#+BEGIN_SRC emacs-lisp
(doom-modeline-def-modeline 'my-main
  '(eldoc bar window-state workspace-name window-number modals matches follow buffer-info remote-host buffer-position word-count parrot selection-info)
  '(compilation objed-state misc-info project-name persp-name battery grip irc mu4e gnus github debug repl lsp minor-modes input-method indent-info buffer-encoding process vcs check time modeline-major-mode-icon))

(doom-modeline-set-modeline 'my-main 'default)
#+END_SRC


An unrealistic modeline with only the icon.

#+BEGIN_SRC emacs-lisp
(doom-modeline-def-modeline 'my-main
  '()
  '(modeline-major-mode-icon))

(doom-modeline-set-modeline 'my-main 'default)
#+END_SRC

* See [[https://github.com/rgkirch/my-emacs-packages][my other emacs packages]]
* License

Copyright (C) 2025 Richie Kirchofer

SPDX-License-Identifier: GPL-3.0-or-later

This program is free software: you can redistribute it and/or modify it under
the terms of the GNU General Public License as published by the Free Software
Foundation, either version 3 of the License, or (at your option) any later
version.

This program is distributed in the hope that it will be useful, but WITHOUT
ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
FOR A PARTICULAR PURPOSE. See the GNU General Public License for more
details.

You should have received a copy of the GNU General Public License along with
this program. If not, see <https://www.gnu.org/licenses/>.
